[2023-01-18T09:23:41.734+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:58:34.441104+00:00 [queued]>
[2023-01-18T09:23:41.743+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:58:34.441104+00:00 [queued]>
[2023-01-18T09:23:41.744+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T09:23:41.744+0000] {taskinstance.py:1284} INFO - Starting attempt 6 of 6
[2023-01-18T09:23:41.745+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T09:23:41.756+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): pull_data> on 2023-01-18 08:58:34.441104+00:00
[2023-01-18T09:23:41.761+0000] {standard_task_runner.py:55} INFO - Started process 3383 to run task
[2023-01-18T09:23:41.766+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v01', 'pull_data', 'manual__2023-01-18T08:58:34.441104+00:00', '--job-id', '1703', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_operator.py', '--cfg-path', '/tmp/tmpn7x72pbd']
[2023-01-18T09:23:41.769+0000] {standard_task_runner.py:83} INFO - Job 1703: Subtask pull_data
[2023-01-18T09:23:41.833+0000] {task_command.py:389} INFO - Running <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:58:34.441104+00:00 [running]> on host 7af0b5bef0dd
[2023-01-18T09:23:41.895+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=malo
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T08:58:34.441104+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T08:58:34.441104+00:00
[2023-01-18T09:23:41.897+0000] {sql.py:253} INFO - Executing: select count(*) from companies where country = Brazil;
[2023-01-18T09:23:41.909+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T09:23:42.035+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T09:23:42.042+0000] {sql.py:364} INFO - Running statement: select count(*) from companies where country = Brazil;, parameters: None
[2023-01-18T09:23:42.044+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "brazil" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                                       ^

[2023-01-18T09:23:42.055+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=our_dag_with_python_operator_v01, task_id=pull_data, execution_date=20230118T085834, start_date=20230118T092341, end_date=20230118T092342
[2023-01-18T09:23:42.065+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1703 for task pull_data (column "brazil" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                                       ^
; 3383)
[2023-01-18T09:23:42.099+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T09:23:42.117+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
