[2023-01-18T08:51:51.727+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [queued]>
[2023-01-18T08:51:51.735+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [queued]>
[2023-01-18T08:51:51.735+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T08:51:51.736+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-18T08:51:51.737+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T08:51:51.746+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): pull_data> on 2023-01-18 08:50:40.178545+00:00
[2023-01-18T08:51:51.752+0000] {standard_task_runner.py:55} INFO - Started process 1323 to run task
[2023-01-18T08:51:51.758+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v01', 'pull_data', 'manual__2023-01-18T08:50:40.178545+00:00', '--job-id', '1686', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_operator.py', '--cfg-path', '/tmp/tmp3eym1u81']
[2023-01-18T08:51:51.760+0000] {standard_task_runner.py:83} INFO - Job 1686: Subtask pull_data
[2023-01-18T08:51:51.829+0000] {task_command.py:389} INFO - Running <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [running]> on host 7af0b5bef0dd
[2023-01-18T08:51:51.894+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=malo
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T08:50:40.178545+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T08:50:40.178545+00:00
[2023-01-18T08:51:51.895+0000] {sql.py:253} INFO - Executing: select count(*) from companies where country = Brazil;
[2023-01-18T08:51:51.906+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T08:51:52.036+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T08:51:52.043+0000] {sql.py:364} INFO - Running statement: select count(*) from companies where country = Brazil;, parameters: None
[2023-01-18T08:51:52.045+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "country" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                             ^
HINT:  Perhaps you meant to reference the column "companies.Country".

[2023-01-18T08:51:52.056+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v01, task_id=pull_data, execution_date=20230118T085040, start_date=20230118T085151, end_date=20230118T085152
[2023-01-18T08:51:52.066+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1686 for task pull_data (column "country" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                             ^
HINT:  Perhaps you meant to reference the column "companies.Country".
; 1323)
[2023-01-18T08:51:52.091+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T08:51:52.110+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
