[2023-01-18T09:12:23.048+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [queued]>
[2023-01-18T09:12:23.056+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [queued]>
[2023-01-18T09:12:23.057+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T09:12:23.057+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 6
[2023-01-18T09:12:23.058+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T09:12:23.069+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): pull_data> on 2023-01-18 08:50:40.178545+00:00
[2023-01-18T09:12:23.074+0000] {standard_task_runner.py:55} INFO - Started process 2645 to run task
[2023-01-18T09:12:23.079+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v01', 'pull_data', 'manual__2023-01-18T08:50:40.178545+00:00', '--job-id', '1695', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_operator.py', '--cfg-path', '/tmp/tmpfkc4a6pg']
[2023-01-18T09:12:23.081+0000] {standard_task_runner.py:83} INFO - Job 1695: Subtask pull_data
[2023-01-18T09:12:23.146+0000] {task_command.py:389} INFO - Running <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [running]> on host 7af0b5bef0dd
[2023-01-18T09:12:23.206+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=malo
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T08:50:40.178545+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T08:50:40.178545+00:00
[2023-01-18T09:12:23.208+0000] {sql.py:253} INFO - Executing: select count(*) from companies where country = Brazil;
[2023-01-18T09:12:23.218+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T09:12:23.351+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T09:12:23.360+0000] {sql.py:364} INFO - Running statement: select count(*) from companies where country = Brazil;, parameters: None
[2023-01-18T09:12:23.362+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "country" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                             ^
HINT:  Perhaps you meant to reference the column "companies.Country".

[2023-01-18T09:12:23.383+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v01, task_id=pull_data, execution_date=20230118T085040, start_date=20230118T091223, end_date=20230118T091223
[2023-01-18T09:12:23.394+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1695 for task pull_data (column "country" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                             ^
HINT:  Perhaps you meant to reference the column "companies.Country".
; 2645)
[2023-01-18T09:12:23.414+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T09:12:23.431+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
