[2023-01-18T09:17:24.778+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [queued]>
[2023-01-18T09:17:24.786+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [queued]>
[2023-01-18T09:17:24.787+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T09:17:24.788+0000] {taskinstance.py:1284} INFO - Starting attempt 6 of 6
[2023-01-18T09:17:24.789+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T09:17:24.799+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): pull_data> on 2023-01-18 08:50:40.178545+00:00
[2023-01-18T09:17:24.805+0000] {standard_task_runner.py:55} INFO - Started process 2976 to run task
[2023-01-18T09:17:24.811+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v01', 'pull_data', 'manual__2023-01-18T08:50:40.178545+00:00', '--job-id', '1700', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_operator.py', '--cfg-path', '/tmp/tmp7847llmb']
[2023-01-18T09:17:24.813+0000] {standard_task_runner.py:83} INFO - Job 1700: Subtask pull_data
[2023-01-18T09:17:24.880+0000] {task_command.py:389} INFO - Running <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [running]> on host 7af0b5bef0dd
[2023-01-18T09:17:24.941+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=malo
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T08:50:40.178545+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T08:50:40.178545+00:00
[2023-01-18T09:17:24.943+0000] {sql.py:253} INFO - Executing: select count(*) from companies where country = Brazil;
[2023-01-18T09:17:24.953+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T09:17:25.081+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T09:17:25.087+0000] {sql.py:364} INFO - Running statement: select count(*) from companies where country = Brazil;, parameters: None
[2023-01-18T09:17:25.089+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "brazil" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                                       ^

[2023-01-18T09:17:25.100+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=our_dag_with_python_operator_v01, task_id=pull_data, execution_date=20230118T085040, start_date=20230118T091724, end_date=20230118T091725
[2023-01-18T09:17:25.109+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1700 for task pull_data (column "brazil" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                                       ^
; 2976)
[2023-01-18T09:17:25.143+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T09:17:25.160+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
