[2023-01-18T09:02:19.282+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [queued]>
[2023-01-18T09:02:19.292+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [queued]>
[2023-01-18T09:02:19.293+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T09:02:19.294+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 6
[2023-01-18T09:02:19.295+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T09:02:19.307+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): pull_data> on 2023-01-18 08:50:40.178545+00:00
[2023-01-18T09:02:19.314+0000] {standard_task_runner.py:55} INFO - Started process 1994 to run task
[2023-01-18T09:02:19.321+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v01', 'pull_data', 'manual__2023-01-18T08:50:40.178545+00:00', '--job-id', '1691', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_operator.py', '--cfg-path', '/tmp/tmpa0snz0ze']
[2023-01-18T09:02:19.324+0000] {standard_task_runner.py:83} INFO - Job 1691: Subtask pull_data
[2023-01-18T09:02:19.404+0000] {task_command.py:389} INFO - Running <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:50:40.178545+00:00 [running]> on host 7af0b5bef0dd
[2023-01-18T09:02:19.476+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=malo
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T08:50:40.178545+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T08:50:40.178545+00:00
[2023-01-18T09:02:19.478+0000] {sql.py:253} INFO - Executing: select count(*) from companies where country = Brazil;
[2023-01-18T09:02:19.489+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T09:02:19.634+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T09:02:19.646+0000] {sql.py:364} INFO - Running statement: select count(*) from companies where country = Brazil;, parameters: None
[2023-01-18T09:02:19.649+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "country" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                             ^
HINT:  Perhaps you meant to reference the column "companies.Country".

[2023-01-18T09:02:19.665+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v01, task_id=pull_data, execution_date=20230118T085040, start_date=20230118T090219, end_date=20230118T090219
[2023-01-18T09:02:19.677+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1691 for task pull_data (column "country" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                             ^
HINT:  Perhaps you meant to reference the column "companies.Country".
; 1994)
[2023-01-18T09:02:19.693+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T09:02:19.712+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
