[2023-01-18T08:51:34.564+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:46:38.034341+00:00 [queued]>
[2023-01-18T08:51:34.573+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:46:38.034341+00:00 [queued]>
[2023-01-18T08:51:34.574+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T08:51:34.574+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 8
[2023-01-18T08:51:34.575+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T08:51:34.586+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): pull_data> on 2023-01-18 08:46:38.034341+00:00
[2023-01-18T08:51:34.592+0000] {standard_task_runner.py:55} INFO - Started process 1295 to run task
[2023-01-18T08:51:34.597+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v01', 'pull_data', 'manual__2023-01-18T08:46:38.034341+00:00', '--job-id', '1685', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_operator.py', '--cfg-path', '/tmp/tmp9bgopiqy']
[2023-01-18T08:51:34.600+0000] {standard_task_runner.py:83} INFO - Job 1685: Subtask pull_data
[2023-01-18T08:51:34.671+0000] {task_command.py:389} INFO - Running <TaskInstance: our_dag_with_python_operator_v01.pull_data manual__2023-01-18T08:46:38.034341+00:00 [running]> on host 7af0b5bef0dd
[2023-01-18T08:51:34.741+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=malo
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T08:46:38.034341+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T08:46:38.034341+00:00
[2023-01-18T08:51:34.743+0000] {sql.py:253} INFO - Executing: select count(*) from companies where country = Brazil;
[2023-01-18T08:51:34.754+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T08:51:34.923+0000] {base.py:73} INFO - Using connection ID 'posgres' for task execution.
[2023-01-18T08:51:34.930+0000] {sql.py:364} INFO - Running statement: select count(*) from companies where country = Brazil;, parameters: None
[2023-01-18T08:51:34.933+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "country" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                             ^
HINT:  Perhaps you meant to reference the column "companies.Country".

[2023-01-18T08:51:34.946+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v01, task_id=pull_data, execution_date=20230118T084638, start_date=20230118T085134, end_date=20230118T085134
[2023-01-18T08:51:34.958+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1685 for task pull_data (column "country" does not exist
LINE 1: select count(*) from companies where country = Brazil;
                                             ^
HINT:  Perhaps you meant to reference the column "companies.Country".
; 1295)
[2023-01-18T08:51:35.015+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T08:51:35.034+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
