[2023-01-16T11:08:43.799+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.great manual__2023-01-16T11:03:41.778517+00:00 [queued]>
[2023-01-16T11:08:43.808+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v01.great manual__2023-01-16T11:03:41.778517+00:00 [queued]>
[2023-01-16T11:08:43.809+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-16T11:08:43.809+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2023-01-16T11:08:43.810+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-16T11:08:43.824+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): great> on 2023-01-16 11:03:41.778517+00:00
[2023-01-16T11:08:43.830+0000] {standard_task_runner.py:55} INFO - Started process 576 to run task
[2023-01-16T11:08:43.835+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v01', 'great', 'manual__2023-01-16T11:03:41.778517+00:00', '--job-id', '1625', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_operator.py', '--cfg-path', '/tmp/tmpvef6j0kg']
[2023-01-16T11:08:43.837+0000] {standard_task_runner.py:83} INFO - Job 1625: Subtask great
[2023-01-16T11:08:43.903+0000] {task_command.py:389} INFO - Running <TaskInstance: our_dag_with_python_operator_v01.great manual__2023-01-16T11:03:41.778517+00:00 [running]> on host 25e249c46b4c
[2023-01-16T11:08:43.965+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=malo
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=great
AIRFLOW_CTX_EXECUTION_DATE=2023-01-16T11:03:41.778517+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-16T11:03:41.778517+00:00
[2023-01-16T11:08:43.975+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_operator.py", line 17, in read_exel
    '/opt/airflow/data/organizations-500000.xlsx')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 521, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-01-16T11:08:43.986+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v01, task_id=great, execution_date=20230116T110341, start_date=20230116T110843, end_date=20230116T110843
[2023-01-16T11:08:43.997+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1625 for task great (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 576)
[2023-01-16T11:08:44.046+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-16T11:08:44.066+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
